### ISSUE TITLE
Selecting a single point, not an area

### ISSUE THREAD

**Issue by Spheerys** [osucomm/geotv#2]
Hi,

I'm interesting by GeoTV for one purpose : geolocate POI on a map.
I don't really need area selecting : just coordonnates of a single point.

Could GeoTV be improved in this way ?
Else, do you know another modx addon to do this stuff ?

**Comment by electrickite** [comment]
Thanks for the suggestion! The newest version of GeoTV (1.0.0) pvovides two TV types, Geographic Area and Geographic Point. Geographic Point allows a user to select one or more points on a map, rather than draw polygons. See the [README](https://github.com/osucomm/geotv/blob/master/README.md) for the details.

Would you mind updating to the latest version and providing feedback?

**Comment by Spheerys** [comment]
I will !
Maybe not next days, but next weeks probably :)
Thanks :)

**Comment by Spheerys** [comment]
Super !
Thank you :)
Yes I will provide you feedback when I will solve my issue https://github.com/electrickite/geotv/issues/1#issuecomment-172969129

**Comment by Spheerys** [comment]
I have tested and it's working perfectly !
It was exactly what I need for my project :)
Thanks x1000

**Comment by electrickite** [comment]
I'm not sure why this issue was re-opened, but I'm closing again unless the new point feature is not working as expected.
